{{- if not .Values.selfSignedOperatorCerts }}
{{- $operatorCerts := splitList "\n" (include "operator.certs" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: cockroach-operator-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ index $operatorCerts 0 }}
  {{ index $operatorCerts 1 }}
  {{ index $operatorCerts 2 }}
{{- end }}
